### ISSUE TITLE
Missing opusXML2docs.pl

### ISSUE THREAD

**Issue by lorelupo** [rbawden/Large-contrastive-pronoun-testset-EN-FR#2]
Hello,

running `bash scripts/setup_opensubs.sh` fails with error.

````
Can't open perl script "scripts/opusXML2docs.pl": No such file or directory
````

Could you please add the missing file?

**Comment by rbawden** [comment]
Hi! Thanks for spotting that. I have added the missing file. Please let me know if you find any other problems!

**Comment by lorelupo** [comment]
Thank you, everything is fine now.
